steps:
- task: UseDotNet@2
  displayName: 'Install .NET 3.1'
  inputs:
    packageType: sdk
    version: 3.1.x

- task: UseDotNet@2
  displayName: 'Install .NET 5.0'
  inputs:
    packageType: sdk
    version: 5.0.x

- task: UseDotNet@2
  displayName: 'Install .NET 6.0'
  inputs:
    packageType: sdk
    version: 6.0.x

- pwsh: |
    dotnet workload install android
    dotnet workload install ios
    dotnet workload install tvos
    dotnet workload install macos

- task: Cache@2
  displayName: Cache NuGet packages
  inputs:
    key: 'nuget | "$(Agent.OS)" | Directory.Packages.props'
    restoreKeys: |
      nuget | "$(Agent.OS)"
      nuget
    path: '$(NUGET_PACKAGES)'
  continueOnError: true

- task: Cache@2
  displayName: Cache Cake tools
  inputs:
    key: '"$(Agent.OS)" | build.cake'
    path: 'tools'
  continueOnError: true

- script: dotnet tool restore
  displayName: Restore dotnet tools