# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MvvmCross
description: > # this means to ignore newlines until "baseurl:"
  MvvmCross is a convention based MVVM framework for Xamarin and Windows,
  with strong community support, filled to the brim with useful features.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.mvvmcross.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MvvmCross
github_username:  MvvmCross
git_repo: MvvmCross

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock

# jekyll-seo-tag config
social:
  name: MvvmCross
  links:
    - https://twitter.com/MvvmCross
    - https://github.com/MvvmCross

logo: /img/MvvmCross-avatar.png

twitter:
  username: MvvmCross

collections:
  documentation:
    output: true
    permalink: /:collection/:path/:title:output_ext

category_order:
  - 'Getting-started'
  - 'Fundamentals'
  - 'Tutorials'
  - 'Platform specifics'
  - 'Upgrading'
  - 'Samples'
  - 'Plugins'
  - 'Testing'
  - 'Contributing'
  - 'Licensing'
